//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class accion_rol
    {
        public int cod_accion_rol { get; set; }
        public Nullable<int> cod_rol { get; set; }
        public Nullable<int> cod_accion_rapida { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual accion_rapida accion_rapida { get; set; }
        public virtual rol rol { get; set; }
    }
}
