//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class accion_rapida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accion_rapida()
        {
            this.accion_rol = new HashSet<accion_rol>();
        }
    
        public int cod_accion_rapida { get; set; }
        public string desc_accion_rapida { get; set; }
        public int mostrar { get; set; }
        public bool borrador_interna { get; set; }
        public bool borrador_entrante { get; set; }
        public bool borrador_saliente { get; set; }
        public bool notificacion_interna { get; set; }
        public bool notificacion_entrante { get; set; }
        public bool notificacion_saliente { get; set; }
        public bool requiere_original { get; set; }
        public bool tarea_pendiente { get; set; }
        public bool tarea_concluida { get; set; }
        public bool req_ruta_pend { get; set; }
        public bool req_ult_original { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accion_rol> accion_rol { get; set; }
    }
}
