//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayuda_rel
    {
        public int cod_ayuda { get; set; }
        public int cod_tema_rel { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ayuda ayuda { get; set; }
        public virtual ayuda ayuda1 { get; set; }
    }
}
