//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ayuda()
        {
            this.ayuda1 = new HashSet<ayuda>();
            this.ayuda_rel = new HashSet<ayuda_rel>();
            this.ayuda_rel1 = new HashSet<ayuda_rel>();
        }
    
        public int cod_ayuda { get; set; }
        public string desc_ayuda { get; set; }
        public Nullable<int> sub_tema_de { get; set; }
        public string contenido { get; set; }
        public string ref_pagina { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ayuda> ayuda1 { get; set; }
        public virtual ayuda ayuda2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ayuda_rel> ayuda_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ayuda_rel> ayuda_rel1 { get; set; }
    }
}
