//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public int cod_cargo { get; set; }
        public string desc_cargo { get; set; }
        public bool local { get; set; }
        public Nullable<int> cod_referencia { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
