//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class carpeta_tematica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carpeta_tematica()
        {
            this.catalogacions = new HashSet<catalogacion>();
            this.grupo_usuario_carpeta_tematica = new HashSet<grupo_usuario_carpeta_tematica>();
        }
    
        public int cod_carpeta_tematica { get; set; }
        public Nullable<int> cod_seccion { get; set; }
        public string desc_carpeta_tematica { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual seccion seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogacion> catalogacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_usuario_carpeta_tematica> grupo_usuario_carpeta_tematica { get; set; }
    }
}
