//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class categ_archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categ_archivo()
        {
            this.folder_archivo = new HashSet<folder_archivo>();
        }
    
        public int cod_categ_archivo { get; set; }
        public string desc_categ_archivo { get; set; }
        public Nullable<int> cod_seccion { get; set; }
        public string comentarios { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual seccion seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<folder_archivo> folder_archivo { get; set; }
    }
}
