//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class columna
    {
        public int cod_columna { get; set; }
        public string nom_tabla { get; set; }
        public string sql_select { get; set; }
        public string sql_select_name { get; set; }
        public bool sql_select_hide { get; set; }
        public bool sql_select_readonly { get; set; }
        public string sql_select_tip { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> posicion_x { get; set; }
        public Nullable<int> posicion_y { get; set; }
        public Nullable<int> cod_select_comando { get; set; }
        public Nullable<int> cod_dep_columna { get; set; }
        public string control { get; set; }
        public string valor_por_defecto { get; set; }
        public string funcion_columna { get; set; }
        public Nullable<int> ancho { get; set; }
        public Nullable<int> alto { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual comando comando { get; set; }
    }
}
