//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class columna1
    {
        public int cod_columna { get; set; }
        public string nom_tabla { get; set; }
        public string sql_select { get; set; }
        public string sql_select_name { get; set; }
        public Nullable<bool> sql_select_hide { get; set; }
        public string sql_select_tip { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
