//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlativos_2
    {
        public int cod_correlativos { get; set; }
        public short cod_tipo_documento { get; set; }
        public Nullable<short> cod_seccion { get; set; }
        public string Alfanumerico { get; set; }
        public Nullable<int> num_max { get; set; }
        public Nullable<System.DateTime> fecha_max { get; set; }
        public int num_ini { get; set; }
    }
}
