//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class correspondencia_para_mostrar
    {
        public int Código { get; set; }
        public string Alerta { get; set; }
        public Nullable<int> Nº_de_HR { get; set; }
        public string Asunto_ { get; set; }
        public string Tipo_Tarea { get; set; }
        public Nullable<System.DateTime> Fecha_Límite { get; set; }
        public string Tipo_Copia { get; set; }
        public string Tipo_Ruta { get; set; }
        public Nullable<System.DateTime> Fecha_de_Envío { get; set; }
        public string Tipo { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Destino_Original { get; set; }
        public string Estado { get; set; }
        public string Prioridad_ { get; set; }
        public string Registró_ { get; set; }
        public string Sección_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Concluido { get; set; }
        public Nullable<int> Cod__Doc_ { get; set; }
        public string Reasignado_a { get; set; }
        public bool Autorizado { get; set; }
        public Nullable<System.DateTime> fecha_rec { get; set; }
        public Nullable<int> regional_reg { get; set; }
    }
}
