//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.con_copia1 = new HashSet<con_copia>();
            this.contenidoes = new HashSet<contenido>();
            this.notificacions = new HashSet<notificacion>();
            this.rutas = new HashSet<ruta>();
            this.libroes = new HashSet<libro>();
        }
    
        public int cod_documento { get; set; }
        public Nullable<int> cod_tipo_dest { get; set; }
        public Nullable<int> cod_tipo_documento { get; set; }
        public Nullable<int> cod_tipo_via { get; set; }
        public string correlativo { get; set; }
        public Nullable<int> num_hoja_ruta { get; set; }
        public Nullable<System.DateTime> fecha_doc { get; set; }
        public string asunto_doc { get; set; }
        public Nullable<int> remitente { get; set; }
        public string nombre_orig { get; set; }
        public Nullable<int> orig_cargo { get; set; }
        public string cargo_orig { get; set; }
        public Nullable<int> orig_seccion { get; set; }
        public string seccion_orig { get; set; }
        public Nullable<int> destinatario { get; set; }
        public string nombre_dest { get; set; }
        public Nullable<int> dest_cargo { get; set; }
        public string cargo_dest { get; set; }
        public string seccion_dest { get; set; }
        public Nullable<int> dest_seccion { get; set; }
        public Nullable<int> via_persona { get; set; }
        public Nullable<int> orig_empresa { get; set; }
        public string empresa_orig { get; set; }
        public Nullable<int> dest_empresa { get; set; }
        public string empresa_dest { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public Nullable<bool> dest_personal { get; set; }
        public Nullable<bool> orig_personal { get; set; }
        public Nullable<int> tipo_datos_orig { get; set; }
        public Nullable<int> tipo_datos_dest { get; set; }
        public string datos_orig { get; set; }
        public string datos_dest { get; set; }
        public string contenido { get; set; }
        public Nullable<int> cod_ref { get; set; }
        public Nullable<int> cod_folder_archivo { get; set; }
        public Nullable<int> ordinal { get; set; }
        public Nullable<int> autogenerado { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> cod_tipo_referencia { get; set; }
        public Nullable<int> fojas { get; set; }
        public string con_copia { get; set; }
        public Nullable<bool> impreso { get; set; }
        public Nullable<int> cod_not_resp { get; set; }
        public Nullable<int> ult_destino { get; set; }
        public string item_type { get; set; }
        public string item_key { get; set; }
        public Nullable<int> numero_hojas { get; set; }
        public Nullable<int> anexos { get; set; }
        public Nullable<bool> cite_generado { get; set; }
        public Nullable<bool> asunto_confidencial { get; set; }
        public Nullable<bool> impreso_libro { get; set; }
        public Nullable<int> cod_seccion_archivo { get; set; }
        public Nullable<int> cod_categ_archivo { get; set; }
        public Nullable<int> cod_tipo_flujo { get; set; }
        public Nullable<int> cod_catalogacion { get; set; }
        public Nullable<int> cod_grupo { get; set; }
        public bool ruta_insertada { get; set; }
        public string usuario_reg { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public Nullable<int> regional_reg { get; set; }
        public Nullable<int> seccion_reg { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public string correlativo_entrante { get; set; }
        public Nullable<System.DateTime> fecha_genera_cite { get; set; }
        public Nullable<int> cod_tipo_tramite { get; set; }
        public Nullable<int> nro_tramite { get; set; }
        public Nullable<int> contrasenia { get; set; }
        public string correlativo_final { get; set; }
        public System.Guid rowguid { get; set; }
        public string dir { get; set; }
        public string texto { get; set; }
    
        public virtual catalogacion catalogacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_copia> con_copia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contenido> contenidoes { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual empresa empresa1 { get; set; }
        public virtual estado estado { get; set; }
        public virtual folder_archivo folder_archivo { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual persona persona { get; set; }
        public virtual persona persona1 { get; set; }
        public virtual seccion seccion { get; set; }
        public virtual seccion seccion1 { get; set; }
        public virtual seccion seccion2 { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual tipo_datos tipo_datos { get; set; }
        public virtual tipo_datos tipo_datos1 { get; set; }
        public virtual tipo_dest tipo_dest { get; set; }
        public virtual tipo_referencia tipo_referencia { get; set; }
        public virtual tipo_via tipo_via { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruta> rutas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libroes { get; set; }
    }
}
