//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_directorio
    {
        public int cod_grupo_directorio { get; set; }
        public int cod_grupo { get; set; }
        public Nullable<int> cod_persona { get; set; }
        public Nullable<int> cod_empresa { get; set; }
        public string persona { get; set; }
        public string empresa { get; set; }
        public string cargo { get; set; }
        public string seccion { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual empresa empresa1 { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual persona persona1 { get; set; }
    }
}
