//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuario_carpeta_tematica
    {
        public int cod_grupo_usuario_carpeta_tematica { get; set; }
        public Nullable<int> cod_grupo_usuario { get; set; }
        public Nullable<int> cod_carpeta_tematica { get; set; }
    
        public virtual carpeta_tematica carpeta_tematica { get; set; }
        public virtual grupo_usuario grupo_usuario { get; set; }
    }
}
