//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grupo_usuario()
        {
            this.grupo_usuario_carpeta_tematica = new HashSet<grupo_usuario_carpeta_tematica>();
            this.usuario_grupo_usuario = new HashSet<usuario_grupo_usuario>();
        }
    
        public int cod_grupo_usuario { get; set; }
        public string desc_grupo_usuario { get; set; }
        public Nullable<int> cod_seccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_usuario_carpeta_tematica> grupo_usuario_carpeta_tematica { get; set; }
        public virtual seccion seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_grupo_usuario> usuario_grupo_usuario { get; set; }
    }
}
