//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libro()
        {
            this.notificacions = new HashSet<notificacion>();
            this.documentoes = new HashSet<documento>();
        }
    
        public int cod_libro { get; set; }
        public int gestion { get; set; }
        public string desc_libro { get; set; }
        public int cod_seccion { get; set; }
        public int ult_hoja { get; set; }
        public int ult_pos { get; set; }
        public int ult_hoja_impresa { get; set; }
        public System.DateTime fecha_limite { get; set; }
        public int max_pos { get; set; }
        public int ult_pos_impresa { get; set; }
        public int cod_tipo_dest { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual seccion seccion { get; set; }
        public virtual tipo_dest tipo_dest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documentoes { get; set; }
    }
}
