//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu()
        {
            this.menu1 = new HashSet<menu>();
            this.parametro_consulta = new HashSet<parametro_consulta>();
            this.rol_menu = new HashSet<rol_menu>();
        }
    
        public int cod_menu { get; set; }
        public Nullable<int> cod_comando { get; set; }
        public Nullable<int> orden { get; set; }
        public string desc_menu { get; set; }
        public Nullable<int> cod_menu_padre { get; set; }
        public string consulta { get; set; }
        public string formulario_accion { get; set; }
        public string nom_tabla_select { get; set; }
        public string nom_tabla { get; set; }
        public int indice_imagen { get; set; }
        public bool es_procedimiento { get; set; }
        public int tipo_menu { get; set; }
        public string col_desc_menu { get; set; }
        public string col_param1 { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual comando comando { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu1 { get; set; }
        public virtual menu menu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parametro_consulta> parametro_consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_menu> rol_menu { get; set; }
    }
}
