//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion_baja
    {
        public int cod_notificacion_baja { get; set; }
        public int cod_notificacion { get; set; }
        public int cod_persona { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual notificacion notificacion { get; set; }
        public virtual persona persona { get; set; }
    }
}
