//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro_sistema
    {
        public int cod_parametro_sistema { get; set; }
        public string nom_parametro_sistema { get; set; }
        public string val_parametro_sistema { get; set; }
        public Nullable<int> tipo_parametro_sistema { get; set; }
        public string desc_parametro_sistema { get; set; }
        public string nom_archivo { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
