//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro_consulta
    {
        public int cod_parametro_consulta { get; set; }
        public int cod_menu { get; set; }
        public string nom_parametro { get; set; }
        public string valor_por_defecto { get; set; }
        public string funcion_parametro { get; set; }
        public int tipo_dato { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
