//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_persona_archivo_general
    {
        public int cod_persona_persona_archivo__general { get; set; }
        public Nullable<int> cod_persona1 { get; set; }
        public Nullable<int> cod_persona2 { get; set; }
        public Nullable<int> cod_seccion { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
