//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla
    {
        public int cod_plantilla { get; set; }
        public int cod_tipo_documento { get; set; }
        public string desc_plantilla { get; set; }
        public string ruta { get; set; }
        public string nom_archivo { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual tipo_documento tipo_documento { get; set; }
    }
}
