//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_menu
    {
        public int cod_rol_menu { get; set; }
        public int cod_rol { get; set; }
        public int cod_menu { get; set; }
        public bool permiso_lectura { get; set; }
        public bool permiso_escritura { get; set; }
        public bool permiso_borrado { get; set; }
        public bool permiso_insercion { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual rol rol { get; set; }
    }
}
