//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_usuario
    {
        public int cod_rol_usuario { get; set; }
        public int cod_rol { get; set; }
        public string cod_usuario { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
