//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seccion()
        {
            this.carpeta_tematica = new HashSet<carpeta_tematica>();
            this.categ_archivo = new HashSet<categ_archivo>();
            this.correlativos = new HashSet<correlativo>();
            this.documentoes = new HashSet<documento>();
            this.documentoes1 = new HashSet<documento>();
            this.documentoes2 = new HashSet<documento>();
            this.grupo_usuario = new HashSet<grupo_usuario>();
            this.libroes = new HashSet<libro>();
            this.persona_firma = new HashSet<persona_firma>();
            this.seccion1 = new HashSet<seccion>();
        }
    
        public int cod_seccion { get; set; }
        public bool local { get; set; }
        public Nullable<int> cod_empresa { get; set; }
        public string desc_seccion { get; set; }
        public Nullable<int> seccion_matriz { get; set; }
        public string secretaria { get; set; }
        public Nullable<int> jefe_seccion { get; set; }
        public bool activo { get; set; }
        public string url_servicio { get; set; }
        public Nullable<int> cod_referencia { get; set; }
        public string sigla { get; set; }
        public Nullable<int> matriz { get; set; }
        public Nullable<int> area { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carpeta_tematica> carpeta_tematica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categ_archivo> categ_archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<correlativo> correlativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documentoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documentoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_usuario> grupo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona_firma> persona_firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seccion> seccion1 { get; set; }
        public virtual seccion seccion2 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
