//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTR_Permisos_TraPer2009
    {
        public decimal Nro_Solicitud { get; set; }
        public Nullable<int> Cod_Persona { get; set; }
        public Nullable<decimal> Gestion { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> Fecha_Permiso { get; set; }
        public Nullable<System.DateTime> De_Horas { get; set; }
        public Nullable<System.DateTime> A_Horas { get; set; }
        public Nullable<int> Minutos { get; set; }
        public Nullable<System.DateTime> Fecha_Solicitud { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Apr_Rec { get; set; }
        public Nullable<int> Cod_Apr_Rec { get; set; }
    }
}
