//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_documento_leido
    {
        public int cod_usuario_documento_leido { get; set; }
        public Nullable<int> cod_persona { get; set; }
        public Nullable<int> cod_documento { get; set; }
        public Nullable<int> cod_notificacion_ult { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
