//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_archivo
    {
        public int Código { get; set; }
        public string Sección { get; set; }
        public string Folder { get; set; }
        public string Categoria { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public string Tipo_Ruta { get; set; }
        public string Prioridad_ { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Vía { get; set; }
        public string Contenido { get; set; }
        public string correlativo { get; set; }
        public string Registró_ { get; set; }
        public Nullable<System.DateTime> Fecha_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Doc_ { get; set; }
        public string Asunto_ { get; set; }
        public string Remitente_Original { get; set; }
        public string Destino_Original { get; set; }
        public string Empresa_Destino { get; set; }
        public string Empresa_Origen { get; set; }
        public Nullable<bool> dest_personal { get; set; }
        public Nullable<bool> orig_personal { get; set; }
        public string Sección_Origen { get; set; }
        public string Sección_Destino { get; set; }
        public string Tipo_de_Datos_Origen { get; set; }
        public string Tipo_de_Datos_Destino { get; set; }
        public string Datos_Origen { get; set; }
        public string Datos_Destino { get; set; }
        public Nullable<int> persona_origen { get; set; }
        public Nullable<int> persona_destino { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public Nullable<int> remitente { get; set; }
        public string desc_tipo_tarea { get; set; }
        public Nullable<System.DateTime> fecha_concluido { get; set; }
        public string desc_folder_archivo { get; set; }
        public string desc_categ_archivo { get; set; }
    }
}
