//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_correlativo_proyecto
    {
        public int Código { get; set; }
        public string Tipo_Documento { get; set; }
        public string Proyecto { get; set; }
        public string Alfanumérico { get; set; }
        public Nullable<int> Máximo { get; set; }
        public Nullable<System.DateTime> Fecha_de_Caducidad { get; set; }
        public int Último_Número { get; set; }
    }
}
