//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_correspondencia_pendiente
    {
        public int Cod__Not_ { get; set; }
        public Nullable<int> Cod__Doc_ { get; set; }
        public Nullable<int> Nº_de_HR { get; set; }
        public string Tipo_Ruta { get; set; }
        public Nullable<System.DateTime> Fecha_de_Envío { get; set; }
        public string Asunto_ { get; set; }
        public string Tipo { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Remitente_Original { get; set; }
        public string Empresa_Origen { get; set; }
        public string Otro_Origen { get; set; }
        public string Destino_Original { get; set; }
        public string Empresa_Destino { get; set; }
        public string Otro_Destino { get; set; }
        public string Estado { get; set; }
        public string Prioridad_ { get; set; }
        public string Vía { get; set; }
        public string Tipo_de_Documento { get; set; }
        public string CITE { get; set; }
        public string Registró_ { get; set; }
        public string Sección { get; set; }
        public Nullable<System.DateTime> Fecha_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Doc_ { get; set; }
        public string Sección_Origen { get; set; }
        public string Cargo_Origen { get; set; }
        public string Sección_Destino { get; set; }
        public string Cargo_Destino { get; set; }
        public string Tipo_de_Tarea { get; set; }
        public Nullable<System.DateTime> Fecha_Límite { get; set; }
        public Nullable<System.DateTime> Fecha_de_Alerta { get; set; }
        public Nullable<System.DateTime> Fecha_Conclusión { get; set; }
        public string Orig__Copia { get; set; }
    }
}
