//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_correspondencia_bandeja_ultimo
    {
        public int Código { get; set; }
        public string Proyecto { get; set; }
        public string Regional { get; set; }
        public string Alerta { get; set; }
        public Nullable<int> C__de_Barras { get; set; }
        public string Nro_HR { get; set; }
        public string Num__HR { get; set; }
        public string Año_HR { get; set; }
        public string Ruta { get; set; }
        public string Fecha_Envío { get; set; }
        public string Asunto { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Tema { get; set; }
        public string Sub_Tema { get; set; }
        public string Ruta_Abierta { get; set; }
        public string Original { get; set; }
        public string Registró { get; set; }
        public string sigla { get; set; }
        public string correlativo { get; set; }
        public Nullable<System.DateTime> fecha_env { get; set; }
        public string Fecha_Limite { get; set; }
        public string desc_tipo_tramite { get; set; }
        public Nullable<int> nro_tramite { get; set; }
        public string Empresa_Origen { get; set; }
        public string Empresa_Destino { get; set; }
        public string Seccion_Origen { get; set; }
        public string seccion_Destino { get; set; }
    }
}
