//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_despacho_zona
    {
        public int Código { get; set; }
        public Nullable<int> Cod__Doc_ { get; set; }
        public string Zona { get; set; }
        public string Ciudad { get; set; }
        public string Empresa_Destino { get; set; }
        public string Dirección { get; set; }
        public Nullable<System.DateTime> Fecha_de_Envío { get; set; }
        public string Asunto_ { get; set; }
        public string Remitente_ { get; set; }
        public string Responzable_de_Despacho_ { get; set; }
        public string Destinatario { get; set; }
        public string correlativo { get; set; }
        public string Prioridad_ { get; set; }
        public string Vía { get; set; }
        public string Sección_Origen { get; set; }
        public string Sección_Destino { get; set; }
        public string Despacho_Reasignado_a_ { get; set; }
        public string Contenido { get; set; }
        public string Empresa_Origen { get; set; }
        public string Otro_Origen { get; set; }
        public string Otro_Destino { get; set; }
        public string Estado { get; set; }
        public string Registró_ { get; set; }
        public string Sección { get; set; }
        public Nullable<System.DateTime> Fecha_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Doc_ { get; set; }
        public Nullable<int> Cod__Tarea { get; set; }
        public Nullable<int> Cod__Tipo_Not_ { get; set; }
        public Nullable<System.DateTime> FC { get; set; }
        public string nombres_persona { get; set; }
        public Nullable<int> cod_ciudad { get; set; }
        public Nullable<int> cod_zona { get; set; }
        public string desc_zona { get; set; }
        public string desc_ciudad { get; set; }
    }
}
