//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_documento_seccion
    {
        public int Cod__Doc_ { get; set; }
        public string Sección_Origen { get; set; }
        public string CITE { get; set; }
        public Nullable<int> Nº_de_HR { get; set; }
        public string Tipo_Ruta { get; set; }
        public string Tipo_de_Documento { get; set; }
        public string Remitente_Original { get; set; }
        public string Empresa_Origen { get; set; }
        public string Destino_Original { get; set; }
        public string Sección_Destino { get; set; }
        public string Empresa_Destino { get; set; }
        public string desc_estado { get; set; }
        public string Asunto_ { get; set; }
    }
}
