//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_documento_ruta
    {
        public int Cod__Doc_ { get; set; }
        public Nullable<int> Nº_de_HR { get; set; }
        public string Tipo_Ruta { get; set; }
        public string Asunto { get; set; }
        public string Tipo_de_Documento { get; set; }
        public Nullable<System.DateTime> Fecha_Doc_ { get; set; }
        public string Proyecto_Remitente { get; set; }
        public string Remitente_Original { get; set; }
        public string Proyecto_Destino { get; set; }
        public string Destinatario_Original { get; set; }
        public string Flujo { get; set; }
        public string Estado { get; set; }
        public string Registró_ { get; set; }
        public System.DateTime Fecha_Reg_ { get; set; }
    }
}
