//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_documento_copia
    {
        public int Código { get; set; }
        public string Estado { get; set; }
        public string Tipo_Ruta { get; set; }
        public string Vía { get; set; }
        public string correlativo { get; set; }
        public string Registró_ { get; set; }
        public string Sección { get; set; }
        public System.DateTime Fecha_Reg_ { get; set; }
        public Nullable<System.DateTime> Fecha_Doc_ { get; set; }
        public string Asunto_ { get; set; }
        public string Remitente_Original { get; set; }
        public string Destino_Original { get; set; }
        public string Empresa_Destino { get; set; }
        public string Empresa_Origen { get; set; }
        public Nullable<bool> dest_personal { get; set; }
        public Nullable<bool> orig_personal { get; set; }
        public string Sección_Origen { get; set; }
        public string Sección_Destino { get; set; }
        public string Tipo_de_Datos_Origen { get; set; }
        public string Tipo_de_Datos_Destino { get; set; }
        public string Datos_Origen { get; set; }
        public string Datos_Destino { get; set; }
        public Nullable<int> remitente { get; set; }
        public string sucursal { get; set; }
        public string desc_tipo_documento { get; set; }
        public string cargo_orig { get; set; }
        public string cargo_dest { get; set; }
        public Nullable<int> via_persona { get; set; }
        public Nullable<int> destinatario { get; set; }
        public string con_copia { get; set; }
        public string nombre_orig { get; set; }
        public string nombre_dest { get; set; }
        public Nullable<int> cod_ref { get; set; }
        public Nullable<int> num_hoja_ruta { get; set; }
        public Nullable<int> hoja_ruta_ref { get; set; }
        public string fax { get; set; }
        public string Persona_Via { get; set; }
        public string Cargo_Via { get; set; }
        public string Seccion_Via { get; set; }
        public string seccion_orig { get; set; }
        public string seccion_dest { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string Persona_Registra { get; set; }
        public string desc_ciudad { get; set; }
        public string prefijo_persona { get; set; }
    }
}
