//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empresa2
    {
        public int Código { get; set; }
        public string Nombre_Razón_Social { get; set; }
        public string sigla { get; set; }
        public string comentarios { get; set; }
        public string sucursal { get; set; }
        public string Tipo_de_Empresa_Rubro { get; set; }
        public string Dirección { get; set; }
        public string Teléfono_1 { get; set; }
        public string Teléfono_2 { get; set; }
        public string fax { get; set; }
        public string País { get; set; }
        public string Ciudad { get; set; }
        public string Zona { get; set; }
        public string e_mail { get; set; }
        public string Web_URL { get; set; }
        public string ruc { get; set; }
        public string casilla { get; set; }
        public string Discado_Directo { get; set; }
        public string usuario_reg { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        public Nullable<int> cod_seccion { get; set; }
    }
}
