//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_folder_archivo
    {
        public int Código { get; set; }
        public string Fólder { get; set; }
        public string Ubicación { get; set; }
        public string Categoría { get; set; }
        public string Sección { get; set; }
        public string Comentarios { get; set; }
    }
}
