//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_grupo_usuario
    {
        public int Codigo { get; set; }
        public string Proyecto { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> cod_seccion { get; set; }
    }
}
