//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_libro_interno
    {
        public Nullable<int> num_hoja_ruta { get; set; }
        public string desc_tipo_dest { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string correlativo { get; set; }
        public string asunto_doc { get; set; }
        public string derivacion { get; set; }
        public Nullable<System.DateTime> fecha_env { get; set; }
        public Nullable<bool> impreso_libro { get; set; }
        public bool impreso_libro_not { get; set; }
        public int cod_documento { get; set; }
        public int cod_notificacion { get; set; }
        public Nullable<int> cod_libro { get; set; }
        public Nullable<int> cod_libro_not { get; set; }
    }
}
