//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_lista_categ_archivo
    {
        public int cod_categ_archivo { get; set; }
        public string desc_categ_archivo { get; set; }
        public Nullable<int> cod_seccion { get; set; }
    }
}
