//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_notificacion_interna_origen_proyecto
    {
        public Nullable<int> Código { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Num__HR { get; set; }
        public Nullable<int> Año_HR { get; set; }
        public string Fecha_Limite { get; set; }
        public string Asunto { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Fecha_Inicio_Ruta { get; set; }
        public string Fecha_Ultima_Ruta { get; set; }
        public string Fecha_Baja_HR { get; set; }
        public string Pry__Tem_ { get; set; }
        public string Tema { get; set; }
        public Nullable<int> cod_tema { get; set; }
        public string Sub_Tema { get; set; }
        public string Proyecto { get; set; }
        public Nullable<int> cod_proyecto { get; set; }
        public int cod_documento { get; set; }
    }
}
