//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_notificacion_todo
    {
        public Nullable<int> Código { get; set; }
        public string Proyecto { get; set; }
        public string Regional { get; set; }
        public string Estado { get; set; }
        public string Pry__Tem_ { get; set; }
        public string Orig__Copia { get; set; }
        public string Num__HR { get; set; }
        public string Año_HR { get; set; }
        public string Ruta { get; set; }
        public string Asunto_ { get; set; }
        public string De_ { get; set; }
        public string Para_ { get; set; }
        public string Fecha_Inicio_Ruta { get; set; }
        public string Dió_Baja { get; set; }
        public string Fecha_Ultima_Ruta { get; set; }
        public string Fecha_Limite { get; set; }
        public string Fecha_Baja_HR { get; set; }
        public string Tema { get; set; }
        public string Sub_Tema { get; set; }
        public string Empresa_Origen { get; set; }
        public string Empresa_Destino { get; set; }
        public string Seccion_Origen { get; set; }
        public string seccion_Destino { get; set; }
    }
}
