//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_persona_con_copia_usuario
    {
        public int Código { get; set; }
        public string Nombres { get; set; }
        public string Usuario { get; set; }
        public string Sección { get; set; }
        public string Cargo { get; set; }
        public string Telf__Dom_ { get; set; }
        public string Telf__Ofi_ { get; set; }
        public Nullable<int> Interno { get; set; }
        public string Movil { get; set; }
        public string Dirección { get; set; }
        public string E_mail { get; set; }
        public string Carnet { get; set; }
        public string Discado_Directo { get; set; }
        public Nullable<int> cod_empresa { get; set; }
    }
}
