//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_plantilla
    {
        public int Código { get; set; }
        public string Tipo_Documento { get; set; }
        public string Plantilla { get; set; }
        public string Archivo { get; set; }
    }
}
