//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_prueba
    {
        public int cod_documento { get; set; }
        public Nullable<int> cod_persona { get; set; }
        public Nullable<int> cod_empresa { get; set; }
        public Nullable<int> dest_empresa { get; set; }
        public string usuario_mod { get; set; }
    }
}
