//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_publico
    {
        public int cod_notificacion { get; set; }
        public string nombres_persona { get; set; }
        public string apellidos_persona { get; set; }
        public string asunto_doc { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string desc_tipo_tramite { get; set; }
        public Nullable<int> nro_tramite { get; set; }
        public Nullable<int> cod_documento { get; set; }
        public string empresa_orig { get; set; }
        public string nombre_orig { get; set; }
        public Nullable<System.DateTime> fecha_doc { get; set; }
        public string contenido { get; set; }
        public string correlativo { get; set; }
        public string usuario_reg { get; set; }
    }
}
