//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_reportes_tematicos
    {
        public int cod_documento { get; set; }
        public Nullable<int> Codigo_de_Barra { get; set; }
        public string No_HR { get; set; }
        public Nullable<System.DateTime> Fecha_Envío { get; set; }
        public string Asunto { get; set; }
        public string De { get; set; }
        public string Para { get; set; }
        public string Empresa_Origen { get; set; }
        public string Registró { get; set; }
        public Nullable<System.DateTime> Fecha_de_Conclusión { get; set; }
    }
}
