//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_seccion_matriz
    {
        public int Código { get; set; }
        public bool local { get; set; }
        public string Regional { get; set; }
        public string Descripción { get; set; }
        public string Dependiente_de { get; set; }
        public string secretaria { get; set; }
        public string Nombre_del_Libro { get; set; }
        public Nullable<int> Nro_Máximo_de_Filas { get; set; }
        public bool activo { get; set; }
        public string sigla { get; set; }
    }
}
