//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tipo_documento_sis
    {
        public int Código { get; set; }
        public string Tipo_de_Documento { get; set; }
        public bool interno { get; set; }
        public bool entrante { get; set; }
        public bool saliente { get; set; }
    }
}
