//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tipo_tarea_sis
    {
        public int Código { get; set; }
        public string Tipo_de_Tarea { get; set; }
        public Nullable<int> meses { get; set; }
        public Nullable<int> Días { get; set; }
        public Nullable<int> horas { get; set; }
        public Nullable<int> minutos { get; set; }
        public Nullable<int> Alerta_Días { get; set; }
        public bool solo_sistema { get; set; }
    }
}
