//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armoniasoft.Corman.Net.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_usuario
    {
        public string Login { get; set; }
        public string Usuario { get; set; }
        public string Descripción { get; set; }
        public string representante { get; set; }
        public string Persona { get; set; }
        public string Nombre_Persona { get; set; }
        public bool activo { get; set; }
    }
}
